name: main-mirror

on:

  push:
    branches:
      - release/*
    tags:
      - v*

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

      - name: Check out tagged version
        uses: actions/checkout@v4

      - name: Mirror to main
        uses: metreeca/gh-mirror-action@v1
        with:
          commit_message: Mirror ${{ github.ref_name }} to main
          branch: main

  publish:

    runs-on: ubuntu-latest
    needs: merge

    steps:

      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update docs
        run: |
          sed "s:{{meta.version}}:${{ github.ref_name }}:g" docs/index.md > README.md
          sed "s:{{meta.version}}:${{ github.ref_name }}:g" docs/template.html > docs/404.html
          touch docs/.nojekyll

      - name: Publish docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docs
