name: main-mirror

on:

  push:
    tags:
      - 'v0.10.*'

jobs:

  merge:

    runs-on: ubuntu-latest

    steps:

      - name: Check out tagged version
        uses: actions/checkout@v4

      - name: Merge into main
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Merge ${{ github.ref_name }} into main
          branch: main

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Update docs
        run: |
          sed "s/{{meta.version}}/${{ github.ref_name }}/g" docs/index.md > README.md
          sed "s/{{meta.version}}/${{ github.ref_name }}/g" docs/404.html  > $$ && mv $$ docs/404.html
          touch docs/.nojekyll

      - name: Publish docs
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update docs
