name: npm-publish

on:

  push:
    tags:
      - v*

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Check out tagged version
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/

      - name: Create README
        run: sed 's:{{meta.version}}:${{ github.ref_name }}:g' docs/index.md > README.md

      - name: Setup environment
        run: npm run setup

      - name: Publish npm package
        run: npm run issue
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
