name: npm-publish

on:

  push:
    tags:
      - '*'

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Check out tagged version
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
